management:
  endpoint:
    logfile:
      external-file: "logs/configserver.log"

spring:
  profiles:
    include:
      - "default"
  liquibase:
    enabled: false
  cloud:
    config:
      server:
        git:
          uri: "/path/to/a/local/git/repository"
