management:
  endpoint:
    logfile:
      external-file: "logs/configserver.log"

spring:
  profiles:
    include:
      - "default"
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:config;DB_CLOSE_DELAY=-1;"
    username: "sa"
    password: "sa"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  liquibase:
    change-log: "classpath:liquibase/liquibase-changelog.xml"
    contexts: "jdbc"
  cloud:
    config:
      server:
        jdbc:
          sql: "select key, value from properties where application=? and profile=? and label=?"
          order: 1
