app:
  name: "@project.artifactId@"
  version: "@project.version@"

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.boip.demo.configServer: INFO

server:
  port: 8888
  servlet:
    context-path: "/configserver"

# for actuator endpoints (spring boot 2)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: "/var/log/cfgserver/configserver.log"
